### ISSUE TITLE
error: snap "powershell" is not available on stable for this architecture (arm64)

### ISSUE THREAD

**Issue by craiglandis** [PowerShell/PowerShell-Snap#55]
[Install PowerShell on Linux](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux) does not mention Ubuntu 19.10.

I tried the 19.04 instructions instead, but it fails saying there is no PowerShell snap for arm64.

I'm running Ubuntu 19.10 Server on a Raspberry Pi 4 (so, ARM64).

# Steps to reproduce

```none
ubuntu@ubuntu:~$ sudo snap install powershell --classic
error: snap "powershell" is not available on stable for this architecture (arm64) but exists on other architectures (amd64).
```
# Expected behavior

Expect there to be a PowerShell snap for ARM64. 

# Actual behavior

```none
error: snap "powershell" is not available on stable for this architecture (arm64) but exists on other architectures (amd64).
```

# Environment data

```none
ubuntu@ubuntu:~$ hostnamectl
   Static hostname: ubuntu
         Icon name: computer
        Machine ID: c2e737ec4d1d40f8b7e6c381f9453a62
           Boot ID: 3f28773124a74a11b72e69a815d6c07d
  Operating System: Ubuntu 19.10
            Kernel: Linux 5.3.0-1014-raspi2
      Architecture: arm64
```

**Comment by snow-jallen** [comment]
That would sure be great if I could easily install powershell on my raspberry pi 4

**Comment by pcgeek86** [comment]
I'm hitting this issue as well, on Raspberry Pi 3 B+ running 64-bit Ubuntu Server 20.04 LTS Focal Fossa.

**Comment by GarrettStrattonTR** [comment]
I'm running 64-bit Ubuntu server 20.10 on my Pi 4 and I ran across the same issue you reported. Instead of installing one of the Ubuntu-specific PowerShell releases, install the latest stable PowerShell release for arm64. 

Cribbing from [installing-powershell-core-on-linux?view=powershell-7.1#raspbian](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#raspbian), do the following:

1. Grab the latest stable release: `wget https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/powershell-7.1.3-linux-arm64.tar.gz`
2. Make folder to put PowerShell: `mkdir ~/powershell`
3. Extract the tarball: `tar -xvf ./powershell-7.1.3-linux-arm64.tar.gz -C ~/powershell`
4. Start PowerShell: `~/powershell/pwsh `
5. Optional, create a symbolic link: `sudo ln -s ~/powershell/pwsh /usr/bin/pwsh`. With a Symlink in place, to start PowerShell you can just run "pwsh"
